---
updates:
  - directory: /
    groups:
      all-dependencies:
        patterns:
          - '*'
    package-ecosystem: mix
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
version: 2
