defmodule AshHq.SqliteRepo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:options) do
      modify :required, :boolean, default: nil
      modify :doc, :text, default: nil
    end

    alter table(:modules) do
      modify :doc, :text, default: nil
      modify :category, :text, default: nil
    end

    alter table(:mix_tasks) do
      modify :doc, :text, default: nil
      modify :category, :text, default: nil
    end

    alter table(:library_versions) do
      modify :hydrated, :boolean, default: nil
    end

    alter table(:libraries) do
      modify :repo_org, :text, default: nil
    end

    alter table(:guides) do
      modify :default, :boolean, default: nil
      modify :category, :text, default: nil
      modify :text, :text, default: nil
    end

    alter table(:functions) do
      modify :doc, :text, default: nil
    end

    alter table(:extensions) do
      modify :doc, :text, default: nil
      modify :default_for_target, :boolean, default: nil
    end

    alter table(:dsls) do
      modify :doc, :text, default: nil
    end
  end

  def down do
    alter table(:dsls) do
      modify :doc, :text, default: ""
    end

    alter table(:extensions) do
      modify :default_for_target, :boolean, default: false
      modify :doc, :text, default: ""
    end

    alter table(:functions) do
      modify :doc, :text, default: ""
    end

    alter table(:guides) do
      modify :text, :text, default: ""
      modify :category, :text, default: "Topics"
      modify :default, :boolean, default: false
    end

    alter table(:libraries) do
      modify :repo_org, :text, default: "ash-project"
    end

    alter table(:library_versions) do
      modify :hydrated, :boolean, default: false
    end

    alter table(:mix_tasks) do
      modify :category, :text, default: "Misc"
      modify :doc, :text, default: ""
    end

    alter table(:modules) do
      modify :category, :text, default: "Misc"
      modify :doc, :text, default: ""
    end

    alter table(:options) do
      modify :doc, :text, default: ""
      modify :required, :boolean, default: false
    end
  end
end