defmodule AshHq.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:options) do
      add :library_version_id,
          references(:dsls, column: :id, name: "options_library_version_id_fkey", type: :uuid),
          null: false
    end
  end

  def down do
    drop constraint(:options, "options_library_version_id_fkey")

    alter table(:options) do
      remove :library_version_id
    end
  end
end