defmodule AshHq.Repo.Migrations.MigrateResources34 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:guides) do
      add(:sanitized_route, :text)
    end

    execute("""
    UPDATE guides SET sanitized_route = REGEXP_REPLACE(guides.route,'[^A-Za-z0-9\/_]/','-','g');
    """)
  end

  def down do
    alter table(:guides) do
      remove(:sanitized_route)
    end
  end
end
