defmodule AshHq.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:options) do
      modify :doc, :text, null: false, default: ""
      add :doc_html, :text
    end

    alter table(:library_versions) do
      modify :doc, :text, default: ""
      add :doc_html, :text
    end

    alter table(:guides) do
      modify :text, :text, default: ""
      add :text_html, :text
    end

    alter table(:dsls) do
      modify :doc, :text, null: false, default: ""
      add :doc_html, :text
    end
  end

  def down do
    alter table(:dsls) do
      remove :doc_html
      modify :doc, :text, null: true, default: nil
    end

    alter table(:guides) do
      remove :text_html
      modify :text, :text, default: nil
    end

    alter table(:library_versions) do
      remove :doc_html
      modify :doc, :text, default: nil
    end

    alter table(:options) do
      remove :doc_html
      modify :doc, :text, null: true, default: nil
    end
  end
end