defmodule AshHq.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:modules) do
      add(:category, :text, null: false, default: "Misc")
    end
  end

  def down do
    alter table(:modules) do
      remove(:category)
    end
  end
end
