defmodule AshHq.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:libraries) do
      add :track_branches, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:libraries) do
      remove :track_branches
    end
  end
end