defmodule AshHq.Repo.Migrations.MigrateResources33 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:libraries) do
      add(:repo_org, :text, null: false, default: "ash-project")
    end
  end

  def down do
    alter table(:libraries) do
      remove(:repo_org)
    end
  end
end
