defmodule AshHq.Repo.Migrations.MigrateResources12 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:extensions) do
      add :type, :text, null: false
    end
  end

  def down do
    alter table(:extensions) do
      remove :type
    end
  end
end