defmodule AshHq.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:dsls) do
      add :recursive_as, :text
    end
  end

  def down do
    alter table(:dsls) do
      remove :recursive_as
    end
  end
end