defmodule AshHq.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:extensions) do
      add :library_version_id,
          references(:library_versions,
            column: :id,
            name: "extensions_library_version_id_fkey",
            type: :uuid
          ),
          null: false
    end
  end

  def down do
    drop constraint(:extensions, "extensions_library_version_id_fkey")

    alter table(:extensions) do
      remove :library_version_id
    end
  end
end