defmodule AshHq.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:options) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:library_versions) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:libraries) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:guides) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:extensions) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:dsls) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end
  end

  def down do
    alter table(:dsls) do
      modify :id, :uuid, default: nil
    end

    alter table(:extensions) do
      modify :id, :uuid, default: nil
    end

    alter table(:guides) do
      modify :id, :uuid, default: nil
    end

    alter table(:libraries) do
      modify :id, :uuid, default: nil
    end

    alter table(:library_versions) do
      modify :id, :uuid, default: nil
    end

    alter table(:options) do
      modify :id, :uuid, default: nil
    end
  end
end