defmodule AshHq.Repo.Migrations.MigrateResources29 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :encrypted_name, :binary
      add :encrypted_address, :binary
      add :shirt_size, :text
    end
  end

  def down do
    alter table(:users) do
      remove :shirt_size
      remove :encrypted_address
      remove :encrypted_name
    end
  end
end