defmodule AshHq.Repo.Migrations.MigrateResources21 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_versions) do
      remove(:default_guide)
      remove(:branch)
    end

    alter table(:libraries) do
      remove(:track_branches)
    end
  end

  def down do
    alter table(:libraries) do
      add(:track_branches, {:array, :text})
    end

    alter table(:library_versions) do
      add(:branch, :boolean, null: false, default: false)
      add(:default_guide, :text)
    end
  end
end
