defmodule AshHq.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:options) do
      add :extension_id,
          references(:extensions, column: :id, name: "options_extension_id_fkey", type: :uuid),
          null: false
    end
  end

  def down do
    drop constraint(:options, "options_extension_id_fkey")

    alter table(:options) do
      remove :extension_id
    end
  end
end