defmodule AshHq.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_versions) do
      remove :doc_html
      remove :doc
    end
  end

  def down do
    alter table(:library_versions) do
      add :doc, :text, null: false, default: ""
      add :doc_html, :text
    end
  end
end
