defmodule AshHq.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:guides) do
      add(:category, :text, default: "Guides")
      add(:route, :text, null: false)
    end
  end

  def down do
    alter table(:guides) do
      remove(:route)
      remove(:category)
    end
  end
end
