defmodule AshHq.Repo.Migrations.MigrateResources32 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:guides) do
      add :default, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:guides) do
      remove :default
    end
  end
end