defmodule AshHq.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:extensions) do
      modify :doc, :text, default: ""
      add :doc_html, :text
    end
  end

  def down do
    alter table(:extensions) do
      remove :doc_html
      modify :doc, :text, default: nil
    end
  end
end