defmodule AshHq.Repo.Migrations.InstallSslinfo do
  @moduledoc """
  Installs any extensions that are mentioned in the repo's `installed_extensions/0` callback

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Removed because fly does not support this
    # execute("CREATE EXTENSION IF NOT EXISTS \"sslinfo\"")
  end

  def down do
    # execute("DROP EXTENSION IF EXISTS \"sslinfo\"")
  end
end
