defmodule AshHq.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:extensions) do
      add :target, :text
      add :default_for_target, :boolean, default: false
    end

    create unique_index(:extensions, [:library_version_id, :name],
             name: "extensions_unique_name_by_library_version_index"
           )
  end

  def down do
    drop_if_exists unique_index(:extensions, [:library_version_id, :name],
                     name: "extensions_unique_name_by_library_version_index"
                   )

    alter table(:extensions) do
      remove :default_for_target
      remove :target
    end
  end
end