defmodule AshHq.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_versions) do
      add(:default_guide, :text, null: false)
    end
  end

  def down do
    alter table(:library_versions) do
      remove(:default_guide)
    end
  end
end
