defmodule AshHq.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:library_versions, [:library_id, :version],
             name: "library_versions_unique_version_for_library_index"
           )
  end

  def down do
    drop_if_exists unique_index(:library_versions, [:library_id, :version],
                     name: "library_versions_unique_version_for_library_index"
                   )
  end
end