defmodule AshHq.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sections, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
    end

    create table(:library_versions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :version, :text, null: false
      add :library_id, :uuid, null: false
    end

    create table(:libraries, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:library_versions) do
      modify :library_id,
             references(:libraries,
               column: :id,
               name: "library_versions_library_id_fkey",
               type: :uuid
             )
    end

    alter table(:libraries) do
      add :name, :text, null: false
    end

    create table(:extensions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
    end

    create table(:entities, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
    end
  end

  def down do
    drop table(:entities)

    drop table(:extensions)

    alter table(:libraries) do
      remove :name
    end

    drop constraint(:library_versions, "library_versions_library_id_fkey")

    alter table(:library_versions) do
      modify :library_id, :uuid
    end

    drop table(:libraries)

    drop table(:library_versions)

    drop table(:sections)
  end
end