defmodule AshHq.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_versions) do
      add :processed, :boolean, default: false
    end
  end

  def down do
    alter table(:library_versions) do
      remove :processed
    end
  end
end