defmodule AshHq.Repo.Migrations.MigrateResources38 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DELETE FROM user_tokens
    """)

    alter table(:user_tokens) do
      add(:subject, :text, null: false)
    end
  end

  def down do
    alter table(:user_tokens) do
      remove(:subject)
    end
  end
end
