defmodule AshHq.Repo.Migrations.MigrateResources58 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    ALTER TABLE discord_messages
      DROP COLUMN searchable
    """)

    drop_if_exists(
      index(:discord_messages, ["searchable"], name: "discord_messages_searchable_index")
    )
  end

  def down do
    create index(:discord_messages, ["searchable"], using: "GIN")

    execute("""
    ALTER TABLE discord_messages
      ADD COLUMN searchable tsvector
      GENERATED ALWAYS AS (
        setweight(to_tsvector('english', content), 'D')
      ) STORED;
    """)
  end
end
