defmodule AshHq.Repo.Migrations.MigrateResources57 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:contributors) do
      add(:order, :bigint, null: false)
    end
  end

  def down do
    alter table(:contributors) do
      remove(:order)
    end
  end
end
