defmodule AshHq.Repo.Migrations.MigrateResources54 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mix_tasks) do
      add(:module_name, :text)
    end
  end

  def down do
    alter table(:mix_tasks) do
      remove(:module_name)
    end
  end
end
