defmodule AshHq.Repo.Migrations.MigrateResources42 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:libraries) do
      add(:mix_project, :text)
    end

    # alter table(:dsls) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :links
    # 
    # end
    # 
  end

  def down do
    # alter table(:dsls) do
    # This is the `down` migration of the statement:
    #
    #     remove :links
    #
    # 
    # add :links, :map
    # end
    # 
    alter table(:libraries) do
      remove(:mix_project)
    end
  end
end
