defmodule AshHq.Repo.Migrations.AddFunctionDeprecationNotices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:functions) do
      add(:deprecated, :text)
    end
  end

  def down do
    alter table(:functions) do
      remove(:deprecated)
    end
  end
end
