defmodule AshHq.Repo.Migrations.MigrateResources56 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:contributors, primary_key: false) do
      add(:id, :bigint, null: false, primary_key: true)
      add(:login, :text, null: false)
      add(:avatar_url, :text, null: false)
      add(:html_url, :text, null: false)
    end
  end

  def down do
    drop(table(:contributors))
  end
end
