defmodule AshHq.Repo.Migrations.MigrateResources53 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:libraries) do
      add :skip_versions, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:libraries) do
      remove :skip_versions
    end
  end
end