defmodule AshHq.Repo.Migrations.MigrateResources41 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_versions) do
      add(:hydrated, :boolean, null: false, default: false)
    end

    alter table(:libraries) do
      add(:module_prefixes, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    alter table(:libraries) do
      remove(:module_prefixes)
    end

    alter table(:library_versions) do
      remove(:hydrated)
    end
  end
end
