defmodule AshHq.Repo.Migrations.MigrateResources52 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:dsls) do
      add(:requires_extension, :text)
    end
  end

  def down do
    alter table(:dsls) do
      remove(:requires_extension)
    end
  end
end
